# Generated by Django 2.2.5 on 2020-04-07 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('text', models.CharField(blank=True, max_length=264)),
                ('author', models.CharField(max_length=264)),
                ('site', models.URLField(blank=True)),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=20, unique=True)),
                ('qname', models.CharField(max_length=264)),
                ('total_que', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuizUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('uname', models.CharField(max_length=264)),
                ('emailid', models.CharField(max_length=264)),
                ('timestamp', models.DateTimeField()),
                ('quecount', models.IntegerField(default=0)),
                ('marksobtained', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=264, unique=True)),
                ('name', models.CharField(max_length=264)),
                ('std', models.IntegerField()),
                ('dob', models.CharField(max_length=264)),
                ('pf', models.CharField(default='Failed', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('English', 'English'), ('Maths', 'Maths'), ('Hindi', 'Hindi'), ('Science', 'Science'), ('Social Studies', 'Social Science'), ('Art', 'Art'), ('Sanskrit', 'Sanskrit')], default='Hindi', max_length=264)),
                ('marks', models.IntegerField()),
                ('max_mark', models.IntegerField(choices=[(20, 20), (50, 50), (100, 100)])),
                ('rollno', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='none', max_length=264)),
                ('last_name', models.CharField(default='none', max_length=264)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='male', max_length=264)),
                ('mob_no', models.CharField(default='9415127397', max_length=10, unique=True)),
                ('designation', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], default='teacher', max_length=264)),
                ('profile_pic', models.ImageField(blank=True, upload_to='media/profile_pics')),
                ('schoolid', models.CharField(max_length=264)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queid', models.CharField(max_length=20, unique=True)),
                ('quename', models.CharField(max_length=264)),
                ('marks', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Questions')),
            ],
        ),
    ]
