# Generated by Django 2.2.5 on 2020-04-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_auto_20200419_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='option4',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
