# Generated by Django 2.2.5 on 2020-04-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_answers_option4'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quecount', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('uid', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quizuser',
            name='marksobtained',
        ),
        migrations.RemoveField(
            model_name='quizuser',
            name='quecount',
        ),
        migrations.RemoveField(
            model_name='quizuser',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='quizuser',
            name='clas',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='quizuser',
            name='password',
            field=models.CharField(default='kcs', max_length=100),
        ),
    ]
