# Generated by Django 2.2.5 on 2020-04-27 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_auto_20200422_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(choices=[('1', 'Option1'), ('2', 'Option1'), ('3', 'Option1'), ('4', 'Option1')], default='Option1', max_length=100),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 13, 43, 14, 167462, tzinfo=utc)),
        ),
    ]
