# Generated by Django 2.2.5 on 2020-05-03 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_auto_20200427_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 12, 14, 25, 203218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quizsubjects',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizsubjects',
            name='max_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizsubjects',
            name='quecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizsubjects',
            name='uid',
            field=models.CharField(max_length=100),
        ),
    ]
