# Generated by Django 2.2.5 on 2020-05-08 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_auto_20200503_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubjects',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 5, 55, 26, 106044, tzinfo=utc)),
        ),
    ]
