# Generated by Django 2.2.5 on 2020-05-08 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_auto_20200508_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 5, 55, 43, 145531, tzinfo=utc)),
        ),
    ]
