# Generated by Django 2.2.5 on 2020-05-08 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_auto_20200508_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 8, 42, 49, 169246, tzinfo=utc)),
        ),
    ]
