# Generated by Django 2.2.5 on 2020-05-08 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_auto_20200508_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 8, 43, 0, 838460, tzinfo=utc)),
        ),
    ]
